In [ ]:
import roboticstoolbox as rtb
import numpy as np

ModuleNotFoundError: No module named 'roboticstoolbox'

In [ ]:

# Define the DH parameters for your 6 DOF robotic arm
# Convention: Modified DH parameters (Denavit-Hartenberg)

# Link | a (m) | alpha (rad) | d (m) | theta (rad) | offset
# -----|-------|-------------|-------|-------------|--------
#  1   | a1    | alpha1      | d1    | theta1      | offset1
#  2   | a2    | alpha2      | d2    | theta2      | offset2
#  ... | ...   | ...         | ...   | ...         | ...
#  6   | a6    | alpha6      | d6    | theta6      | offset6


# Example DH parameters (replace with your actual values)
# These are just example values, make sure to use your robot's specifications.
# Note: Python's trigonometric functions use radians.

a1 = 0.1  # Example: Link 1 length
alpha1 = 0.0  # Example: Link 1 twist angle
d1 = 0.2    # Example: Link 1 offset
offset1 = 0.0 # Example: Link 1 joint offset (if any)

a2 = 0.2  # Example: Link 2 length
alpha2 = np.pi/2  # Example: Link 2 twist angle (90 degrees)
d2 = 0.0    # Example: Link 2 offset
offset2 = 0.0

a3 = 0.15 # Example: Link 3 length
alpha3 = 0.0  # Example: Link 3 twist angle
d3 = 0.1    # Example: Link 3 offset
offset3 = 0.0

a4 = 0.2  # Example: Link 4 length
alpha4 = np.pi/2  # Example: Link 4 twist angle (90 degrees)
d4 = 0.0    # Example: Link 4 offset
offset4 = 0.0

a5 = 0.1  # Example: Link 5 length
alpha5 = 0.0  # Example: Link 5 twist angle
d5 = 0.1    # Example: Link 5 offset
offset5 = 0.0

a6 = 0.05  # Example: Link 6 length
alpha6 = 0.0  # Example: Link 6 twist angle
d6 = 0.0    # Example: Link 6 offset
offset6 = 0.0


# Create the DH matrix for each link.  Robotic Toolbox uses a specific order.
#  [ a, alpha, d, theta, offset]

L1 = rtb.Link(a=a1, alpha=alpha1, d=d1, qlim=[-np.pi, np.pi], offset=offset1) # qlim: joint limits (radians)
L2 = rtb.Link(a=a2, alpha=alpha2, d=d2, qlim=[-np.pi, np.pi], offset=offset2)
L3 = rtb.Link(a=a3, alpha=alpha3, d=d3, qlim=[-np.pi, np.pi], offset=offset3)
L4 = rtb.Link(a=a4, alpha=alpha4, d=d4, qlim=[-np.pi, np.pi], offset=offset4)
L5 = rtb.Link(a=a5, alpha=alpha5, d=d5, qlim=[-np.pi, np.pi], offset=offset5)
L6 = rtb.Link(a=a6, alpha=alpha6, d=d6, qlim=[-np.pi, np.pi], offset=offset6)


# Create the robot object.
robot = rtb.DHRobot([L1, L2, L3, L4, L5, L6], name='My 6 DOF Robot')  # Give your robot a name

# Display the robot's DH parameters.
print(robot)

# Example Usage:
# You can now use the 'robot' object for various robotic tasks.

# Forward Kinematics:
q = [0, 0, 0, 0, 0, 0]  # Example joint angles (replace with your values)
T = robot.fkine(q)  # Get the end-effector transformation matrix
print("Forward Kinematics:\n", T)

# Inverse Kinematics (more complex, often requires specific solvers):
# ... (see Robotic Toolbox documentation for IK)

# Trajectory generation, dynamics, etc.
# ... (explore other features of the Robotic Toolbox)

# Plot the robot
robot.plot(q)


# To visualize the robot: (requires spatialmath-python)
# robot.plot(q)  # q is your joint angle vector

In [2]:
import numpy as np

In [6]:
cir = [0.0, np.pi/4, 3*np.pi/4, np.pi, 5*np.pi/4, 3*np.pi/2 ,7*np.pi/4 ,2*np.pi ,]

print([np.array(np.array([x, 0.0 ,0.0, 0.0, 0.0, 0.0])) for x in cir])

[array([0., 0., 0., 0., 0., 0.]), array([0.78539816, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([2.35619449, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([3.14159265, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([3.92699082, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([4.71238898, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([5.49778714, 0.        , 0.        , 0.        , 0.        ,
       0.        ]), array([6.28318531, 0.        , 0.        , 0.        , 0.        ,
       0.        ])]


In [7]:
tethas = [np.array([x, 0.0 ,0.0, 0.0, 0.0, 0.0]) for x in cir]

tethas

[array([0., 0., 0., 0., 0., 0.]),
 array([0.78539816, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([2.35619449, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([3.14159265, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([3.92699082, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([4.71238898, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([5.49778714, 0.        , 0.        , 0.        , 0.        ,
        0.        ]),
 array([6.28318531, 0.        , 0.        , 0.        , 0.        ,
        0.        ])]